language: python

python:
  - "2.7"

# command to install dependencies
install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install pylint
  - pip install elasticsearch
  - pip install -e .
  
# command to run tests
script:
  - py.test --cov=indexer tests/ && pylint --disable=missing-docstring indexer

after_success:
  - coveralls
