language: python

python:
  - "2.7"

# command to install dependencies
install:
  - pip install -e .
  - pip install pytest pytest-cov
  - pip install coveralls
  
# command to run tests
script:
  - py.test

after_success:
  - coveralls
